apiVersion: v2
name: mautrix-linkedin
description: Helm chart for mautrix-linkedin
home: https://docs.mau.fi/bridges/go/linkedin/
sources:
  - https://github.com/mautrix/linkedin
type: application
version: 0.1.1
appVersion: "v0.2602.0"
dependencies:
  - name: mautrix-go-base
    version: 0.1.4
    repository: file://../mautrix-go-base
