apiVersion: v2
name: mautrix-bluesky
description: Helm chart for mautrix-bluesky
home: https://docs.mau.fi/bridges/go/bluesky/
sources:
  - https://github.com/mautrix/bluesky
type: application
version: 1.0.1
appVersion: "v0.2510.0"
dependencies:
  - name: mautrix-go-base
    version: 1.0.1
    repository: file://../mautrix-go-base
