{{- if eq (include "ntfy.metricsEnabled" . | trim) "true" }}
{{- $baseLabels := include "ntfy.labels" . | fromYaml -}}
{{- $customLabels := default (dict) .Values.serviceMonitor.labels -}}
{{- $serviceMonitorLabels := merge $baseLabels $customLabels -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ntfy.fullname" . }}
  labels:
    {{- toYaml $serviceMonitorLabels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ntfy.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
