apiVersion: v2
name: mautrix-go-base
description: Shared library templates for mautrix Go bridge Helm charts
home: https://docs.mau.fi/bridges/go/
sources:
  - https://github.com/mautrix
  - https://github.com/cyclikal94/matrix-helm-charts
type: library
version: 0.1.0
appVersion: "0.0.0"
